#
/control/verbose 2
/run/verbose 1
#
/testhadr/det/setIsotopeMat Cs137 55 137 1.93 g/cm3
/testhadr/det/setThickness 1 cm
/testhadr/det/setSizeYZ 1 cm
#
/run/initialize
#
/gun/particle neutron
/gun/energy 25 meV
/testhadr/gun/beamSize 25 mm
/testhadr/gun/beamTime 3 year
#
/analysis/setFileName Cs137
/analysis/h1/set 4  100  0 6 MeV   #gamma
/analysis/h1/set 14 100  0 4 year  #gamma
#
/run/printProgress 1000
/run/beamOn 10000
